import type { ReactDiffViewerStylesOverride } from "react-diff-viewer-continued";

const diffStyles = {
  variables: {
    light: {
      diffViewerBackground: "var(--color-surface)",
      diffViewerColor: "var(--color-gray-800)",
      addedBackground: "var(--color-emerald-50)",
      addedColor: "var(--color-emerald-800)",
      removedBackground: "var(--color-red-50)",
      removedColor: "var(--color-red-800)",
      wordAddedBackground: "var(--color-emerald-200)",
      wordRemovedBackground: "var(--color-red-200)",
      addedGutterBackground: "var(--color-emerald-100)",
      removedGutterBackground: "var(--color-red-100)",
      gutterBackground: "var(--color-gray-100)",
      gutterBackgroundDark: "var(--color-gray-100)",
      highlightBackground: "var(--color-yellow-50)",
      highlightGutterBackground: "var(--color-yellow-100)",
      codeFoldGutterBackground: "var(--color-blue-100)",
      codeFoldBackground: "var(--color-blue-50)",
      emptyLineBackground: "var(--color-gray-50)",
      gutterColor: "var(--color-gray-800)",
      addedGutterColor: "var(--color-gray-800)",
      removedGutterColor: "var(--color-gray-800)",
      codeFoldContentColor: "var(--color-gray-800)",
      diffViewerTitleBackground: "var(--color-gray-50)",
      diffViewerTitleColor: "var(--color-gray-800)",
      diffViewerTitleBorderColor: "var(--color-border)",
    },
    dark: {
      diffViewerBackground: "var(--color-surface)",
      diffViewerColor: "var(--color-gray-50)",
      addedBackground: "var(--color-teal-900)",
      addedColor: "var(--color-teal-50)",
      removedBackground: "var(--color-orange-900)",
      removedColor: "var(--color-orange-50)",
      wordAddedBackground: "var(--color-teal-800)",
      wordRemovedBackground: "var(--color-orange-900)",
      addedGutterBackground: "var(--color-teal-900)",
      removedGutterBackground: "var(--color-red-900)",
      gutterBackground: "var(--color-gray-800)",
      gutterBackgroundDark: "var(--color-gray-800)",
      highlightBackground: "var(--color-gray-700)",
      highlightGutterBackground: "var(--color-gray-900)",
      codeFoldGutterBackground: "var(--color-gray-800)",
      codeFoldBackground: "var(--color-gray-800)",
      emptyLineBackground: "var(--color-gray-700)",
      gutterColor: "var(--color-gray-500)",
      addedGutterColor: "var(--color-gray-400)",
      removedGutterColor: "var(--color-gray-400)",
      codeFoldContentColor: "var(--color-gray-600)",
      diffViewerTitleBackground: "var(--color-gray-800)",
      diffViewerTitleColor: "var(--color-gray-500)",
      diffViewerTitleBorderColor: "var(--color-border)",
    },
  },
  diffContainer: {
    width: "100%",
    height: "100%",
    minHeight: "120px", // --spacing(30)
  },
} satisfies ReactDiffViewerStylesOverride;

export { diffStyles };
