/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as staticIndexRouteImport } from './routes/(static)/index'
import { Route as staticTagsIndexRouteImport } from './routes/(static)/tags/index'
import { Route as appViewerIndexRouteImport } from './routes/(app)/viewer/index'
import { Route as appEditorIndexRouteImport } from './routes/(app)/editor/index'

const staticIndexRoute = staticIndexRouteImport.update({
  id: '/(static)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const staticTagsIndexRoute = staticTagsIndexRouteImport.update({
  id: '/(static)/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const appViewerIndexRoute = appViewerIndexRouteImport.update({
  id: '/(app)/viewer/',
  path: '/viewer/',
  getParentRoute: () => rootRouteImport,
} as any)
const appEditorIndexRoute = appEditorIndexRouteImport.update({
  id: '/(app)/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof staticIndexRoute
  '/editor/': typeof appEditorIndexRoute
  '/viewer/': typeof appViewerIndexRoute
  '/tags/': typeof staticTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof staticIndexRoute
  '/editor': typeof appEditorIndexRoute
  '/viewer': typeof appViewerIndexRoute
  '/tags': typeof staticTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(static)/': typeof staticIndexRoute
  '/(app)/editor/': typeof appEditorIndexRoute
  '/(app)/viewer/': typeof appViewerIndexRoute
  '/(static)/tags/': typeof staticTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor/' | '/viewer/' | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/viewer' | '/tags'
  id:
    | '__root__'
    | '/(static)/'
    | '/(app)/editor/'
    | '/(app)/viewer/'
    | '/(static)/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  staticIndexRoute: typeof staticIndexRoute
  appEditorIndexRoute: typeof appEditorIndexRoute
  appViewerIndexRoute: typeof appViewerIndexRoute
  staticTagsIndexRoute: typeof staticTagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(static)/': {
      id: '/(static)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof staticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/tags/': {
      id: '/(static)/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof staticTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/viewer/': {
      id: '/(app)/viewer/'
      path: '/viewer'
      fullPath: '/viewer/'
      preLoaderRoute: typeof appViewerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/editor/': {
      id: '/(app)/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof appEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  staticIndexRoute: staticIndexRoute,
  appEditorIndexRoute: appEditorIndexRoute,
  appViewerIndexRoute: appViewerIndexRoute,
  staticTagsIndexRoute: staticTagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
