/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as staticIndexRouteImport } from './routes/(static)/index'
import { Route as appviewerViewerRouteImport } from './routes/(app)/(viewer)/viewer'
import { Route as appeditorEditorRouteImport } from './routes/(app)/(editor)/editor'

const staticIndexRoute = staticIndexRouteImport.update({
  id: '/(static)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appviewerViewerRoute = appviewerViewerRouteImport.update({
  id: '/(app)/(viewer)/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const appeditorEditorRoute = appeditorEditorRouteImport.update({
  id: '/(app)/(editor)/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof staticIndexRoute
  '/editor': typeof appeditorEditorRoute
  '/viewer': typeof appviewerViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof staticIndexRoute
  '/editor': typeof appeditorEditorRoute
  '/viewer': typeof appviewerViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(static)/': typeof staticIndexRoute
  '/(app)/(editor)/editor': typeof appeditorEditorRoute
  '/(app)/(viewer)/viewer': typeof appviewerViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/viewer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/viewer'
  id:
    | '__root__'
    | '/(static)/'
    | '/(app)/(editor)/editor'
    | '/(app)/(viewer)/viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  staticIndexRoute: typeof staticIndexRoute
  appeditorEditorRoute: typeof appeditorEditorRoute
  appviewerViewerRoute: typeof appviewerViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(static)/': {
      id: '/(static)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof staticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(viewer)/viewer': {
      id: '/(app)/(viewer)/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof appviewerViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(editor)/editor': {
      id: '/(app)/(editor)/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof appeditorEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  staticIndexRoute: staticIndexRoute,
  appeditorEditorRoute: appeditorEditorRoute,
  appviewerViewerRoute: appviewerViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
